[package]
name = "fubuki"
version = "0.5.0"
authors = ["xty <xutianyi1999@live.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
log4rs = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
rand = "0.8"
socket2 = "0.4"
parking_lot = { version = "0.12", features = ["hardware-lock-elision"] }
anyhow = "1"
mimalloc = { version = "*", default-features = false }
ahash = "0.8"
futures-util = "0.3"
md5 = "0.7"
ipnet = { version = "2", features = ["serde"] }
arc-swap = "1"
human-panic = "1"
hyper = { version = "0.14", features = ["server", "client", "http1", "tcp"] }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
prettytable-rs = "0.10"
scopeguard = "1"
arrayvec = { version = "0.7", features = ["serde"] }
static-files = { version = "0.2", optional = true }
gethostname = "0.4"

net-route = { git = "https://github.com/johnyburd/net-route.git" }
netconfig = { git = "https://github.com/xutianyi1999/netconfig.git" }
hostsfile = { git = "https://github.com/tonarino/innernet.git" }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
tun = { version = "0.5", features = ["async"] }

[target.'cfg(target_os = "windows")'.dependencies]
simple_wintun = { git = "https://github.com/xutianyi1999/SimpleWintun.git", features = ["async"] }

[build-dependencies]
static-files = { version = "0.2", optional = true }

[patch.crates-io]
advmac = { git = "https://github.com/xutianyi1999/advmac.git" }

[features]
web = ["static-files"]

[profile.release]
lto = true
codegen-units = 1
