[package]
name = "fubuki"
version = "0.5.6"
authors = ["xty <xutianyi1999@live.com>"]
edition = "2021"

[lib]
# differentiate from bin
name = "fubukil"
crate-type = ["lib", "staticlib", "cdylib"]
path = "src/lib.rs"

[[bin]]
name = "fubuki"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
log4rs = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
rand = "0.8"
socket2 = "0.4"
parking_lot = "0.12"
anyhow = "1"
ahash = "0.8"
futures-util = "0.3"
ipnet = { version = "2", features = ["serde"] }
arc-swap = "1"
human-panic = "1"
hyper = { version = "0.14", features = ["server", "client", "http1", "tcp"] }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
prettytable-rs = "0.10"
scopeguard = "1"
arrayvec = { version = "0.7", features = ["serde"] }
static-files = { version = "0.2", optional = true }
gethostname = "0.4"
flume = { version = "0.11", default-features = false, features = ["async", "spin"] }
sha2 = "0.10"
digest = "0.10"
crossbeam-utils = "0.8"
libloading = "0.8"

linear-map = { git = "https://github.com/contain-rs/linear-map.git" }
klask = { git = "https://github.com/xosxos/klask.git", optional = true }
net-route = { git = "https://github.com/johnyburd/net-route.git" }
netconfig = { git = "https://github.com/xutianyi1999/netconfig.git" }
hostsfile = { git = "https://github.com/tonarino/innernet.git" }

mimalloc = { version = "*", default-features = false, optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
tempfile = "3"

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
tun = { version = "0.6", features = ["async"] }

[target.'cfg(target_os = "windows")'.dependencies]
simple_wintun = { git = "https://github.com/xutianyi1999/SimpleWintun.git", features = ["async"] }

[target.'cfg(target_os = "windows")'.build-dependencies]
winres = "0.1"

[build-dependencies]
static-files = { version = "0.2", optional = true }

[patch.crates-io]
advmac = { git = "https://github.com/xutianyi1999/advmac.git" }

[features]
default = ["mimalloc"]
web = ["static-files"]
gui = ["klask"]
hash-routing-table = []

[profile.release]
lto = true
codegen-units = 1
