name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        include:
          - target: aarch64-linux-android
            os: ubuntu-latest
            build_tool: cross

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          cargo install cross --git https://github.com/cross-rs/cross
        if: matrix.target == 'aarch64-linux-android'
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          target: ${{ matrix.target }}
          # (required)
          bin: fubuki
          include: target/${{ matrix.target }}/release/libfubukil.so
          # (optional) On which platform to distribute the `.tar.gz` file.
          # [default value: unix]
          # [possible values: all, unix, windows, none]
          tar: unix
          # (optional) On which platform to distribute the `.zip` file.
          # [default value: windows]
          # [possible values: all, unix, windows, none]
          zip: windows
          build_tool: ${{ matrix.build_tool }}
          no-default-features: true
          features: ${{ matrix.features }}
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTUP_TOOLCHAIN: nightly
          CARGO_TERM_COLOR: always
